Added Styling to book store app
mosidrum/bookstore pull request #5
Opened 2023-06-16 08:35 UTC by mosidrum

**I finished styling the nook store app and I also generated random numbers and chapters to serve as the progress and current chapters for each book, The progress and chapters cant be added to the API, so it regenerates at every refresh or when a book is added.**

2023-06-16 09:32 UTC, tufoinnkuo10 requested changes
Hi @mosidrum 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Gitflow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ design well followed

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-06-16 09:32 UTC, tufoinnkuo10 commented on src/styles/Book.scss
> +      height: 100px;
- [ ] please, like mentioned in your project guidelines, Your final design should match Zeplin's design (this includes all elements + the same styling). Please kindly implement the different colors on the book title, author, genre, chapter, completed, comments etc. like in the original design.
- [ ] Also kindly ensure the book page title is aligned with the book's like in the original design.
- [ ] please, the user icon placeholder is aligned with the book cards on the right. Kindly implement that.
- [ ] please kindly add the extra margin under the form like in the design and ensure the add new book header and form should be aligned with the book cards. . nice work
- [ ] kindly add little extra margin left and right to the cards so the original design can be followed.
yours

![Screenshot (1139)_LI](https://github.com/mosidrum/bookstore/assets/65298048/981f0dd7-1604-460e-a5c4-2796830dafd4)
original design.
![Screenshot (1141)](https://github.com/mosidrum/bookstore/assets/65298048/7c25fbe7-4083-43ba-9d9d-b4467cd2cfb7)

2023-06-16 09:32 UTC, tufoinnkuo10 commented on src/styles/App.scss
> +  /* stylelint-disable */
- [ ] please, for good CSS practices, kindly remove the disable stylint and fix it properly. This will help your work become clean.

2023-06-16 09:32 UTC, tufoinnkuo10 commented on src/styles/Book.scss
> +          // font-weight: 200;
- [ ] kindly remove commented styles for clean code practices.

2023-06-17 00:40 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @mosidrum, 👋 👋 

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous revieer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

### To Highlight :1st_place_medal: 

- Descriptive Pull Request title and summary. ✔️
- Styling of the bookstore CMS project ✔️
- Zeplin Design template used for the design ✔️
- There is good use of Git flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-17 01:10 UTC, merged